[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 10

[theme]
primaryColor = "#0B7285"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#102A43"
font = "sans serif"
